import Image from 'next/image'
import Head from 'next/head'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Contact from '@/components/Contact'


export default function Home() {
  return (
    <>
    <Head>
        <title>Infinity Branding</title>
        <meta name="description" content="Generated by Infinity Branding" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpeg" />
      </Head>
    <main className="px-6 sm:px-12 md:px-24 lg:px-36 max-w-[1600px] min-h-screen mx-auto">
      <Hero/>
      <About/>
      <Contact/>
    </main>
    </>
  )
}
